In [1]:
! ls preproc

PreprocessedPerceptionDataSubject1.h5
PreprocessedPerceptionDataSubject1.h5.zip
PreprocessedPerceptionDataSubject2.h5
PreprocessedPerceptionDataSubject3.h5
PreprocessedSleepDataSubject1.h5
PreprocessedSleepDataSubject2.h5
PreprocessedSleepDataSubject3.h5
propsSubject1.h5
propsSubject2.h5
propsSubject3.h5


In [2]:
import h5py
import os

In [3]:
root = "preproc"
perc = os.path.join(root, "PreprocessedPerceptionDataSubject1.h5")
sleep = os.path.join(root, "PreprocessedSleepDataSubject1.h5")
props = os.path.join(root, "propsSubject1.h5")

In [4]:
dfile = h5py.File(sleep, "r")
dfile.keys()

<KeysViewHDF5 ['data', 'metaData', 'metaDefinition']>

In [5]:
for key in dfile.keys():
    dset = dfile[key]
    try:
        print(key, dset.shape, dset.dtype, dset[0], end="\n\n")
    except:
        print(key, dset, type(key), end="\n\n")

data (235, 4039) float64 [-1.23439404 -0.48702744  1.19918902 ...  1.          1.
  1.        ]

metaData <HDF5 group "/metaData" (43 members)> <class 'str'>

metaDefinition (43,) |S33 b'0 = not voxelData, 1 = voxelData'



In [6]:
tfile = h5py.File(os.path.join(root, "PreprocessedSleepDataSubject2.h5"), "r")
tfile["data"].shape

(198, 3981)

In [7]:
data = dfile["data"]
mdata = dfile["metaData"]
mdef = dfile["metaDefinition"]
for i, key in enumerate(mdata):
    print(i, key, mdata[key].shape, " -- ",mdef[i])

0 EEG_sleep_score (1, 4039)  --  b'0 = not voxelData, 1 = voxelData'
1 FFA (1, 4039)  --  b'Value = X coordinate'
2 HVC (1, 4039)  --  b'Value = Y coordinate'
3 LOC (1, 4039)  --  b'Value = Z coordinate'
4 LVC (1, 4039)  --  b'0 = not FFA voxel, 1 = FFA voxel'
5 PPA (1, 4039)  --  b'0 = not HVC voxel, 1 = HVC voxel'
6 Synset_building_ID_02913152 (1, 4039)  --  b'0 = not LOC voxel, 1 = LOC voxel'
7 Synset_chair_ID_03001627 (1, 4039)  --  b'0 = not LVC voxel, 1 = LVC voxel'
8 Synset_character_ID_06818970 (1, 4039)  --  b'0 = not PPA voxel, 1 = PPA voxel'
9 Synset_clothing_ID_03051540 (1, 4039)  --  b'0 = not V1 voxel, 1 = V1 voxel'
10 Synset_code_ID_06355894 (1, 4039)  --  b'0 = not V2 voxel, 1 = V2 voxel'
11 Synset_cognition_ID_00023271 (1, 4039)  --  b'0 = not V3 voxel, 1 = V3 voxel'
12 Synset_external_body_part_ID_05225090 (1, 4039)  --  b'0 = not label, 1 = label'
13 Synset_geographical_area_ID_08574314 (1, 4039)  --  b'0 = absent, 1 = present'
14 Synset_girl_ID_10129825 (1, 4039)  -

In [8]:
pfile = h5py.File(props, "r")
pfile.keys()

<KeysViewHDF5 ['roiMask', 'roiNames', 'synsetNames', 'synsetPairs', 'xyz']>

In [9]:

for key in pfile.keys():
    dset = pfile[key]
    try:
        print(key, dset.shape, dset.dtype, dset[0], end="\n\n")
    except:
        print(key, dset, type(key), end="\n\n")

roiMask (8, 4010) float64 [0. 0. 0. ... 0. 0. 0.]

roiNames (8,) |S4 b'FFA'

synsetNames (26,) |S38 b'Synset_male_ID_09624168'

synsetPairs (201, 2) |S38 [b'Synset_character_ID_06818970' b'Synset_male_ID_09624168']

xyz (3, 4010) float64 [-67.5 -67.5 -67.5 ...  64.5  64.5  64.5]



In [10]:
rmask = pfile["roiMask"]
rnames = pfile["roiNames"]
xyz = pfile["xyz"]

print(rmask[0, :].sum(), rnames[0])
print(xyz[:, 2])

for region in range(len(rnames)):
    numel = rmask[region].sum() # number of "1" elements in the roi masks
    numel_d = sum(mdata[rnames[region]][0]) # number of "1" elements in corresponding mdata masks
    print(rnames[region], " -- ", numel, " -- ", numel_d) # should both be the same

537.0 b'FFA'
[-67.5 -43.5  -4.5]
b'FFA'  --  537.0  --  537.0
b'HVC'  --  1956.0  --  1956.0
b'LOC'  --  523.0  --  523.0
b'LVC'  --  2054.0  --  2054.0
b'PPA'  --  353.0  --  353.0
b'V1'  --  885.0  --  885.0
b'V2'  --  901.0  --  901.0
b'V3'  --  728.0  --  728.0


In [11]:
print(data.shape)
ffa_mask = rmask[0].astype(bool)
print(ffa_mask.shape)

(235, 4039)
(4010,)


In [12]:
data[-1, 4009:]

array([  1.97166996,   1.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   1.        ,
        26.        , 235.        ])

In [13]:
import numpy as np
import pandas as pd

In [14]:
dfile = h5py.File(sleep, "r") #data file

data = dfile["data"]
mdata = dfile["metaData"]

#convert from h5 to a dictionary of np arrays, which pandas understands
mdata_dict_arr = {key: np.squeeze(np.array(val)) for key, val in mdata.items()}

meta_df = pd.DataFrame.from_dict(mdata_dict_arr)
data_df = np.array(data)

print(meta_df.shape)
meta_df.head()

(4039, 43)


EEG_sleep_score  FFA  HVC  LOC  LVC  PPA  Synset_building_ID_02913152  \
0              0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
1              0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
2              0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
3              0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
4              0.0  0.0  1.0  1.0  0.0  0.0                          0.0   

   Synset_chair_ID_03001627  Synset_character_ID_06818970  \
0                       0.0                           0.0   
1                       0.0                           0.0   
2                       0.0                           0.0   
3                       0.0                           0.0   
4                       0.0                           0.0   

   Synset_clothing_ID_03051540  ...   V2   V3     X     Y    Z  design  label  \
0                          0.0  ...  0.0  0.0 -67.5 -46.5 -1.5     0.0    0.0   
1                          0.0  ...  0.0  0.0 -67.5 -46.5  1.5     0.0    0.0   
2                          0.0  ...  0.0  0.0 -67.5 -43.5 -4.5     0.0    0.0   
3                          0.0  ...  0.0  0.0 -67.5 -43.5 -1.5     0.0    0.0   
4                          0.0  ...  0.0  0.0 -64.5 -52.5 -4.5     0.0    0.0   

   sample_number  session_number  voxelData  
0            0.0             0.0        1.0  
1            0.0             0.0        1.0  
2            0.0             0.0        1.0  
3            0.0             0.0        1.0  
4            0.0             0.0        1.0  

[5 rows x 43 columns]

In [15]:
print(data_df.shape)

(235, 4039)


In [16]:
data_df

array([[-1.23439404e+00, -4.87027437e-01,  1.19918902e+00, ...,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.63373625e+00,  5.24539088e+00, -1.69498203e+00, ...,
         1.00000000e+00,  1.00000000e+00,  2.00000000e+00],
       [ 4.01640746e-01,  3.25192376e+00, -1.38049469e+00, ...,
         1.00000000e+00,  1.00000000e+00,  3.00000000e+00],
       ...,
       [-2.85550630e+00, -2.69055550e+00, -1.17711014e+00, ...,
         1.00000000e+00,  2.60000000e+01,  2.33000000e+02],
       [-1.89436357e-01, -1.59084747e+00,  2.13385080e+00, ...,
         1.00000000e+00,  2.60000000e+01,  2.34000000e+02],
       [-1.89219074e+00, -2.45376516e+00,  3.57550935e+00, ...,
         1.00000000e+00,  2.60000000e+01,  2.35000000e+02]])

In [33]:
import utils

masks, data =  utils.load_data(1)

In [18]:
masks.head()

EEG_sleep_score  FFA  HVC  LOC  LVC  PPA  Synset_building_ID_02913152  \
0              0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
1              0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
2              0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
3              0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
4              0.0  0.0  1.0  1.0  0.0  0.0                          0.0   

   Synset_chair_ID_03001627  Synset_character_ID_06818970  \
0                       0.0                           0.0   
1                       0.0                           0.0   
2                       0.0                           0.0   
3                       0.0                           0.0   
4                       0.0                           0.0   

   Synset_clothing_ID_03051540  ...   V2   V3     X     Y    Z  design  label  \
0                          0.0  ...  0.0  0.0 -67.5 -46.5 -1.5     0.0    0.0   
1                          0.0  ...  0.0  0.0 -67.5 -46.5  1.5     0.0    0.0   
2                          0.0  ...  0.0  0.0 -67.5 -43.5 -4.5     0.0    0.0   
3                          0.0  ...  0.0  0.0 -67.5 -43.5 -1.5     0.0    0.0   
4                          0.0  ...  0.0  0.0 -64.5 -52.5 -4.5     0.0    0.0   

   sample_number  session_number  voxelData  
0            0.0             0.0        1.0  
1            0.0             0.0        1.0  
2            0.0             0.0        1.0  
3            0.0             0.0        1.0  
4            0.0             0.0        1.0  

[5 rows x 43 columns]

In [21]:
data

array([[-1.23439404e+00, -4.87027437e-01,  1.19918902e+00, ...,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.63373625e+00,  5.24539088e+00, -1.69498203e+00, ...,
         1.00000000e+00,  1.00000000e+00,  2.00000000e+00],
       [ 4.01640746e-01,  3.25192376e+00, -1.38049469e+00, ...,
         1.00000000e+00,  1.00000000e+00,  3.00000000e+00],
       ...,
       [-2.85550630e+00, -2.69055550e+00, -1.17711014e+00, ...,
         1.00000000e+00,  2.60000000e+01,  2.33000000e+02],
       [-1.89436357e-01, -1.59084747e+00,  2.13385080e+00, ...,
         1.00000000e+00,  2.60000000e+01,  2.34000000e+02],
       [-1.89219074e+00, -2.45376516e+00,  3.57550935e+00, ...,
         1.00000000e+00,  2.60000000e+01,  2.35000000e+02]])

In [19]:
print(f"data shape: {data.shape}")

data shape: (235, 4039)


In [23]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
import time

from sklearn.model_selection import train_test_split
from utils import load_data

In [24]:
print(masks.shape, data.shape)

(4039, 43) (235, 4039)


In [26]:
masks

EEG_sleep_score  FFA  HVC  LOC  LVC  PPA  Synset_building_ID_02913152  \
0                 0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
1                 0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
2                 0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
3                 0.0  0.0  1.0  0.0  0.0  0.0                          0.0   
4                 0.0  0.0  1.0  1.0  0.0  0.0                          0.0   
...               ...  ...  ...  ...  ...  ...                          ...   
4034              0.0  0.0  0.0  0.0  0.0  0.0                          0.0   
4035              0.0  0.0  0.0  0.0  0.0  0.0                          0.0   
4036              1.0  0.0  0.0  0.0  0.0  0.0                          0.0   
4037              0.0  0.0  0.0  0.0  0.0  0.0                          0.0   
4038              0.0  0.0  0.0  0.0  0.0  0.0                          0.0   

      Synset_chair_ID_03001627  Synset_character_ID_06818970  \
0                          0.0                           0.0   
1                          0.0                           0.0   
2                          0.0                           0.0   
3                          0.0                           0.0   
4                          0.0                           0.0   
...                        ...                           ...   
4034                       0.0                           0.0   
4035                       0.0                           0.0   
4036                       0.0                           0.0   
4037                       0.0                           0.0   
4038                       0.0                           0.0   

      Synset_clothing_ID_03051540  ...   V2   V3     X     Y    Z  design  \
0                             0.0  ...  0.0  0.0 -67.5 -46.5 -1.5     0.0   
1                             0.0  ...  0.0  0.0 -67.5 -46.5  1.5     0.0   
2                             0.0  ...  0.0  0.0 -67.5 -43.5 -4.5     0.0   
3                             0.0  ...  0.0  0.0 -67.5 -43.5 -1.5     0.0   
4                             0.0  ...  0.0  0.0 -64.5 -52.5 -4.5     0.0   
...                           ...  ...  ...  ...   ...   ...  ...     ...   
4034                          0.0  ...  0.0  0.0   0.0   0.0  0.0     0.0   
4035                          0.0  ...  0.0  0.0   0.0   0.0  0.0     0.0   
4036                          0.0  ...  0.0  0.0   0.0   0.0  0.0     0.0   
4037                          0.0  ...  0.0  0.0   0.0   0.0  0.0     1.0   
4038                          0.0  ...  0.0  0.0   0.0   0.0  0.0     1.0   

      label  sample_number  session_number  voxelData  
0       0.0            0.0             0.0        1.0  
1       0.0            0.0             0.0        1.0  
2       0.0            0.0             0.0        1.0  
3       0.0            0.0             0.0        1.0  
4       0.0            0.0             0.0        1.0  
...     ...            ...             ...        ...  
4034    1.0            0.0             0.0        0.0  
4035    1.0            0.0             0.0        0.0  
4036    1.0            0.0             0.0        0.0  
4037    0.0            0.0             1.0        0.0  
4038    0.0            1.0             0.0        0.0  

[4039 rows x 43 columns]

In [27]:
?DataHandler

Object `DataHandler` not found.


In [28]:
from utils import load_data, DataHandler

In [37]:
datahandler = DataHandler(masks, data, test_size=0.2)
trainx = datahandler.get_feature("FFA", "train")
trainx

array([[ 3.13479111,  1.17658321,  6.50440403, ..., -2.1551804 ,
         1.91754033,  2.31447163],
       [-1.48573836, -0.68248116, -1.84439159, ...,  0.04894037,
        -0.14469601,  0.03699679],
       [ 0.48925988,  0.12592435,  1.00365015, ...,  2.81133496,
         1.84680094,  2.29134114],
       ...,
       [ 3.18379007,  2.1517474 ,  2.51530899, ..., -1.59040023,
         8.58549543,  5.78614014],
       [-1.60172866, -0.13283255,  0.10489304, ..., -0.38968208,
        -1.71083441, -0.3821176 ],
       [-0.49848494,  0.34180902, -0.20512824, ...,  1.8354502 ,
         2.79222125,  2.1105833 ]])